name: Deploy Medusa Backend

   on:
     push:
       branches:
         - main

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Log in to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v2
           with:
             region: ${{ secrets.AWS_REGION }}

         - name: Build Docker image
           run: |
             docker build -t medusa-backend .
             docker tag medusa-backend:latest ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest

         - name: Push Docker image to ECR
           run: |
             docker push ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest

         - name: Download ECS Task Definition
           run: |
             aws ecs describe-task-definition --task-definition medusa-task > task-def.json

         - name: Update ECS Task Definition
           run: |
             sed -i 's|<IMAGE_URI>|${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest|' task-def.json
             echo "Updated image in task definition"

         - name: Register updated Task Definition
           run: |
             aws ecs register-task-definition \
               --family medusa-task \
               --cli-input-json file://task-def.json

         - name: Deploy to ECS
           run: |
             aws ecs update-service \
               --cluster medusa-cluster \
               --service medusa-service \
               --force-new-deployment
